version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 5
  - package-ecosystem: "nuget"
    directory: "/"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 5
