// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qorpe.Infrastructure.Data;

#nullable disable

namespace Qorpe.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240819150637_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Qorpe.Domain.Entities.ActiveHealthCheckConfig", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HealthCheckConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Interval")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Policy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Query")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timeout")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckConfigId")
                        .IsUnique();

                    b.ToTable("ActiveHealthCheckConfigs");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.ClusterConfig", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClusterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadBalancingPolicy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClusterConfigs");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.ClusterConfigMetadata", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ClusterConfigMetadata");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.Destination", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.DestinationConfig", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Health")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId")
                        .IsUnique();

                    b.ToTable("DestinationConfigs");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.DestinationConfigMetadata", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("DestinationConfigMetadata");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.ForwarderRequestConfig", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityTimeout")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("AllowResponseBuffering")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ClusterConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VersionPolicy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterConfigId")
                        .IsUnique();

                    b.ToTable("ForwarderRequestConfigs");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.HealthCheckConfig", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvailableDestinationsPolicy")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClusterConfigId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterConfigId")
                        .IsUnique();

                    b.ToTable("HealthCheckConfigs");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.HttpClientConfig", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ClusterConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DangerousAcceptAnyServerCertificate")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("EnableMultipleHttp2Connections")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxConnectionsPerServer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestHeaderEncoding")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseHeaderEncoding")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SslProtocols")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterConfigId")
                        .IsUnique();

                    b.ToTable("HttpClientConfigs");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.PassiveHealthCheckConfig", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HealthCheckConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Policy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivationPeriod")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckConfigId")
                        .IsUnique();

                    b.ToTable("PassiveHealthCheckConfigs");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.RouteConfig", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorizationPolicy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClusterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorsPolicy")
                        .HasColumnType("TEXT");

                    b.Property<long?>("MaxRequestBodySize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputCachePolicy")
                        .HasColumnType("TEXT");

                    b.Property<string>("RateLimiterPolicy")
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timeout")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeoutPolicy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RouteConfigs");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.RouteConfigMetadata", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("RouteConfigMetadata");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.RouteHeader", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCaseSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RouteMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Values")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RouteMatchId");

                    b.ToTable("RouteHeaders");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.RouteMatch", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hosts")
                        .HasColumnType("TEXT");

                    b.Property<string>("Methods")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RouteConfigId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RouteConfigId")
                        .IsUnique();

                    b.ToTable("RouteMatches");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.RouteQueryParameter", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCaseSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RouteMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Values")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RouteMatchId");

                    b.ToTable("RouteQueryParameters");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.SessionAffinityConfig", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AffinityKeyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClusterConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailurePolicy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Policy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClusterConfigId")
                        .IsUnique();

                    b.ToTable("SessionAffinityConfigs");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.SessionAffinityCookieConfig", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Domain")
                        .HasColumnType("TEXT");

                    b.Property<string>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HttpOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsEssential")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaxAge")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SameSite")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecurePolicy")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SessionAffinityConfigId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionAffinityConfigId")
                        .IsUnique();

                    b.ToTable("SessionAffinityCookieConfigs");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.Transform", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RouteConfigId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RouteConfigId");

                    b.ToTable("Transforms");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.TransformMetadata", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("TransformMetadata");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.WebProxyConfig", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("BypassOnLocal")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HttpClientConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("UseDefaultCredentials")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HttpClientConfigId")
                        .IsUnique();

                    b.ToTable("WebProxyConfigs");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.ActiveHealthCheckConfig", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.HealthCheckConfig", null)
                        .WithOne("Active")
                        .HasForeignKey("Qorpe.Domain.Entities.ActiveHealthCheckConfig", "HealthCheckConfigId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.ClusterConfigMetadata", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.ClusterConfig", null)
                        .WithMany("Metadata")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.Destination", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.ClusterConfig", null)
                        .WithMany("Destinations")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.DestinationConfig", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.Destination", null)
                        .WithOne("Value")
                        .HasForeignKey("Qorpe.Domain.Entities.DestinationConfig", "DestinationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.DestinationConfigMetadata", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.DestinationConfig", null)
                        .WithMany("Metadata")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.ForwarderRequestConfig", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.ClusterConfig", null)
                        .WithOne("HttpRequest")
                        .HasForeignKey("Qorpe.Domain.Entities.ForwarderRequestConfig", "ClusterConfigId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.HealthCheckConfig", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.ClusterConfig", null)
                        .WithOne("HealthCheck")
                        .HasForeignKey("Qorpe.Domain.Entities.HealthCheckConfig", "ClusterConfigId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.HttpClientConfig", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.ClusterConfig", null)
                        .WithOne("HttpClient")
                        .HasForeignKey("Qorpe.Domain.Entities.HttpClientConfig", "ClusterConfigId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.PassiveHealthCheckConfig", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.HealthCheckConfig", null)
                        .WithOne("Passive")
                        .HasForeignKey("Qorpe.Domain.Entities.PassiveHealthCheckConfig", "HealthCheckConfigId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.RouteConfigMetadata", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.RouteConfig", null)
                        .WithMany("Metadata")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.RouteHeader", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.RouteMatch", null)
                        .WithMany("Headers")
                        .HasForeignKey("RouteMatchId");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.RouteMatch", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.RouteConfig", null)
                        .WithOne("Match")
                        .HasForeignKey("Qorpe.Domain.Entities.RouteMatch", "RouteConfigId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.RouteQueryParameter", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.RouteMatch", null)
                        .WithMany("QueryParameters")
                        .HasForeignKey("RouteMatchId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.SessionAffinityConfig", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.ClusterConfig", null)
                        .WithOne("SessionAffinity")
                        .HasForeignKey("Qorpe.Domain.Entities.SessionAffinityConfig", "ClusterConfigId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.SessionAffinityCookieConfig", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.SessionAffinityConfig", null)
                        .WithOne("Cookie")
                        .HasForeignKey("Qorpe.Domain.Entities.SessionAffinityCookieConfig", "SessionAffinityConfigId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.Transform", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.RouteConfig", null)
                        .WithMany("Transforms")
                        .HasForeignKey("RouteConfigId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.TransformMetadata", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.Transform", null)
                        .WithMany("Metadata")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.WebProxyConfig", b =>
                {
                    b.HasOne("Qorpe.Domain.Entities.HttpClientConfig", null)
                        .WithOne("WebProxy")
                        .HasForeignKey("Qorpe.Domain.Entities.WebProxyConfig", "HttpClientConfigId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.ClusterConfig", b =>
                {
                    b.Navigation("Destinations");

                    b.Navigation("HealthCheck");

                    b.Navigation("HttpClient");

                    b.Navigation("HttpRequest");

                    b.Navigation("Metadata");

                    b.Navigation("SessionAffinity");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.Destination", b =>
                {
                    b.Navigation("Value");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.DestinationConfig", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.HealthCheckConfig", b =>
                {
                    b.Navigation("Active");

                    b.Navigation("Passive");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.HttpClientConfig", b =>
                {
                    b.Navigation("WebProxy");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.RouteConfig", b =>
                {
                    b.Navigation("Match");

                    b.Navigation("Metadata");

                    b.Navigation("Transforms");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.RouteMatch", b =>
                {
                    b.Navigation("Headers");

                    b.Navigation("QueryParameters");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.SessionAffinityConfig", b =>
                {
                    b.Navigation("Cookie");
                });

            modelBuilder.Entity("Qorpe.Domain.Entities.Transform", b =>
                {
                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
