name: CI (.NET)
on:
  pull_request:
    paths:
      - "**/*.cs"
      - "**/*.csproj"
      - "**/*.sln"
      - ".github/workflows/ci-dotnet.yml"
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x
      - run: dotnet --info
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage" --verbosity normal
